version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: server
      POSTGRES_DB: market
      POSTGRES_PASSWORD: 123456
    networks:
      - shopnet
      
  server:
    build: .
    image: market:latest
    ports:
        - "5000:5000"
    networks:
      - shopnet
      
networks:
  shopnet:
